### ISSUE TITLE
Use do-release-upgrade

### ISSUE THREAD

**Issue by SuperSandro2000** [nemchik/after-install#1]
https://github.com/nemchik/after-install/blob/95ee0da3a7b9c850d6918bb54d72b62fc790c4b7/after-install-ubuntu.sh#L56

``do-release-upgrade´´ is recommended on Ubuntu. See https://help.ubuntu.com/lts/serverguide/installing-upgrading.html

**Comment by nemchik** [comment]
I don't think I want that in here. That would upgrade from for example Ubuntu 18.10 to 19.04. I don't think that would be something you would do after installing a fresh copy of 18.10 (or any version). It makes more sense to use the iso for the version of the OS you want. `do-release-upgrade` is something I run as needed after the OS is installed and running and a new version becomes available.

**Comment by SuperSandro2000** [comment]
dist-upgrade does the same.

**Comment by nemchik** [comment]
That's actually not true https://serverfault.com/questions/322810/whats-the-difference-between-apt-get-dist-upgrade-and-do-release-upgrade they do different things.
